# Generated by Django 5.2.8 on 2025-11-30 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concessionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('siret', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('auto', 'Automobile'), ('moto', 'Moto')], max_length=4)),
                ('marque', models.CharField(max_length=64)),
                ('chevaux', models.IntegerField()),
                ('prix_ht', models.FloatField()),
                ('concessionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='concession.concessionnaire')),
            ],
        ),
    ]
